### ISSUE TITLE
Add a new domain 

### ISSUE THREAD

**Issue by rrbanda** [instructlab/taxonomy#1087]
A domain named `culture` . It  could have qna around topics like open practices organization culture related .

Not available in present list at https://github.com/instructlab/taxonomy/blob/main/knowledge/knowledge_domains.md

**Comment by jjasghar** [comment]
Thank you for that suggestion, but i think this was submitted before we decided to "lean" on the Wikipedia taxonomy tree.
```
Social sciences
   Social sciences, sociology & anthropology
   Political science
   Economics
   Public administration & military science
   Social problems & social services
   Education
   Commerce, communications & transportation
   Customs, etiquette & folklore
```

Culture _could_ fit inside of "customs, etiquette, folklore" but I'll let @mcorbin-ibm or @obuzek talk about any reason we should create a specific `culture` directory.

**Comment by mcorbin-ibm** [comment]
@jjasghar I think that the list of [knowledge domains](https://github.com/instructlab/taxonomy/blob/main/knowledge/knowledge_domains.md) should be updated to mirror the [Wikipedia subjects](https://en.wikipedia.org/wiki/Wikipedia:Contents) instead, since we are basing our taxonomy and knowledge off of Wikipedia to start? (This is what I am putting together in my proposal to revise/reorganize the main levels of our taxonomy tree.)

If we agree to that premise, then adding "Culture" as a knowledge domain makes great sense.  (And, we'd need to completely revise the other list of main knowledge domains to match/sync/move under Wikipedia's subjects.)

**Comment by juliadenham** [comment]
Closing as we are open to many domains!
