### ISSUE TITLE
Pull Request and Issue templates make generic references to "model"

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/taxonomy#1107]
T4R - generally we support users using one of two models in InstructLab - `merlinite` and `granite` - but various Pull Request and Issue templates just ask users about "model" inputs and outputs - we should make this clearer as to what users should actually be using for their taxonomy contributions

**Comment by wking** [comment]
Alternatively, we can ask them to specify which model they used or suggest they copy/paste the output that mentions that.  Because today's Granite is presumably going to be a fair bit different from next year's Granite, and the goal with the taxonomy repo is to collect skills/knowledge that are useful somewhere, and not necessarily only skills that are useful for one particular model today.  Or is there an expectation that we prune skills/knowledge that are no longer useful for one particular model today?  Because I can see maintenance savings in that kind of pruning, but also a chance at making some potential user with a not-all-that-smart base model sad, and balancing the maintenance cost vs. potential use seems hard.

**Comment by lehors** [comment]
I agree with @wking that we should ask people which model they used (including the version). Getting that info makes it possible to implement various policies later on.
