### ISSUE TITLE
Horse Surfing

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#842]
**Topic:** Horse surfing involves one person riding either kite-board, surfboard, wake-board, or skim-board, while being towed behind a horse, ridden by a second person, through shallow water.

**Folder location:** taxonomy/knowledge/sports/horse_surfing

**Downloads:** 
- qna.yaml: [horse_surfing.txt](https://github.com/instructlab/taxonomy/files/15226836/horse_surfing.txt) 
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226149/horse-surfing-attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Horse_surfing

**Comment by wking** [comment]
Looks like both #860 and #863 are aiming at this one?  @ishaksyed, @chrimage, did you want to discuss here or work out plans to collaborate?

Looks like #863's `seed_examples` are currently empty, and perhaps you just want to close that one?  I'm a bit unclear on how the verifier isn't complaining, because both the [v1][1] and [v2][2] schema set `minLength: 1` there.

[1]: https://github.com/instructlab/schema/blob/262ed1d06cd8c1b51e510d98cd7c2dd717e85650/v1/knowledge.json#L44
[2]: https://github.com/instructlab/schema/blame/262ed1d06cd8c1b51e510d98cd7c2dd717e85650/v2/knowledge.json#L46

**Comment by wking** [comment]
Ah, looks like @tayyabr93's also aiming at horse surfing in #859.  Join us to discuss who/how should land what in this space :)

**Comment by chrimage** [comment]
I closed #863, looks like I forgot to hit save before committing. My apologies.

**Comment by kelbrown20** [comment]
Got a lot of great contributions for this one! Closing for scannability, proceeding with the contributions
